### PR TITLE
Clarify initial state when creating reconciler

### PR DESCRIPTION
**Pull request by DjebbZ**
Since the `Usage` example simply a number as the state, the current use of a map made it hard for me to grasp when this map was reused since the rest of the example manipulates the number directly. I propose using nil and a small clarification of the `Controller` section.

### CODE REVIEW

**Comment by DjebbZ** [comment]
It's especially since I come from a React/Redux background and in Redux the initial state is used consistently throughout reducers. Here your pattern of separating the state when creating the reconciler and the `:init` event that actually sets up the initial state enhanced the confusion. 

Not saying the `:init` pattern is a bad idea, quite the opposite actually :+1:

**Comment by roman01la** [comment]
I think this need to be clarified further.

An atom passed into reconciler is a map where every controller stores its state as a value of a key, where a key is a name of a controller. And initial state of a controller is defined in controller's `:init` method.

```cjl
;; controllers map
{:counter control
 :users control}

;; `:counter` controller
(defmethod control :init []
  0)

;; `:users` controller
(defmethod control :init []
  [])

;; state after `:init` phase
(atom {:counter 0
            :users []})
```

Does it makes sense?

**Comment by DjebbZ** [comment]
Ow. Are you saying that the key of a controller in the controllers map **defines** the corresponding key in the state (*Redux-style*) ?

If so, indeed this should be clarified, and it should be clear that the third argument of controller is not the **whole** state but the value **at the controller's key**.

Does it make sense too ? :wink:

**Comment by DjebbZ** [comment]
I would also add that have to manually specify the `:state` key and its value when creating a reconciler is unecessary and error-prone since if the controller's key defines the corresponding key in the state, state is defacto an atom with a map in it. Said in another way, `{:state (atom {})}` is mandatory in the current design, hence unecessary and could lead to think to the state could be modeled as we wish (even if still an atom).

**Comment by roman01la** [comment]
Answering to previous reply:
Yes. It also makes it possible to set initial state of a controller in-place when creating an atom, but it is more convenient to have `:init` method in a controller for this. Scrum intentionally allows to define and pass an atom explicitly into reconciler to make it possible to setup global watchers on the atom.

Could you please update this PR?

**Comment by DjebbZ** [comment]
Your answer explains why my second comment is wrong. Didn't think of a global watchers.

Will update the PR pretty soon. Thanks a lot for your replies.

**Comment by DjebbZ** [comment]
Done ! Ended up a bit long, but I think it makes scrum much clearer for beginners. Really hope you'll like it !

**Comment by roman01la** [comment]
Thanks! Just merged it. I've also adjusted and rephrased some wordings.

**Comment by DjebbZ** [comment]
Very happy I've helped ! I understand how to use Scrum much better now and I hope others will too.

**Pull request merged**
